export const people = [
    {
      name: { title: "Miss", first: "Sangeetha", last: "Hiremath" },
      gender: "female",
      email: "sangeetha.hiremath@example.com",
      location: {
        country: "India",
        state: "Gujarat",
        city: "Kakinada",
        street: { number: 702, name: "Camac St" },
      },
      dateOfBirth: "47-01-03",
      profilePicture: "https://randomuser.me/api/portraits/women/89.jpg",
    },
    {
      name: { title: "Mrs", first: "Christine", last: "Staff" },
      gender: "female",
      email: "christine.staff@example.com",
      location: {
        country: "Norway",
        state: "Møre og Romsdal",
        city: "Kjøllefjord",
        street: { number: 8649, name: "Bergkrystallen" },
      },
      dateOfBirth: "71-08-02",
      profilePicture: "https://randomuser.me/api/portraits/women/93.jpg",
    },
    {
      name: { title: "Mr", first: "Dhiraj", last: "Thampy" },
      gender: "male",
      email: "dhiraj.thampy@example.com",
      location: {
        country: "India",
        state: "Tripura",
        city: "Navi Mumbai",
        street: { number: 6432, name: "Rani No Hajiro" },
      },
      dateOfBirth: "87-08-06",
      profilePicture: "https://randomuser.me/api/portraits/men/59.jpg",
    },
    {
      name: { title: "Mrs", first: "Leja", last: "Bjørnsen" },
      gender: "female",
      email: "leja.bjornsen@example.com",
      location: {
        country: "Norway",
        state: "Hedmark",
        city: "Lyngseidet",
        street: { number: 4010, name: "Smedstusvingen" },
      },
      dateOfBirth: "83-01-04",
      profilePicture: "https://randomuser.me/api/portraits/women/96.jpg",
    },
    {
      name: { title: "Mrs", first: "Nella", last: "Wiita" },
      gender: "female",
      email: "nella.wiita@example.com",
      location: {
        country: "Finland",
        state: "Southern Savonia",
        city: "Turku",
        street: { number: 5369, name: "Hämeenkatu" },
      },
      dateOfBirth: "92-11-03",
      profilePicture: "https://randomuser.me/api/portraits/women/47.jpg",
    },
    {
      name: { title: "Miss", first: "Nina", last: "Živadinović" },
      gender: "female",
      email: "nina.zivadinovic@example.com",
      location: {
        country: "Serbia",
        state: "Šumadija",
        city: "Bač",
        street: { number: 3844, name: "Dobrivoja Jovanovića" },
      },
      dateOfBirth: "67-05-02",
      profilePicture: "https://randomuser.me/api/portraits/women/52.jpg",
    },
    {
      name: { title: "Mr", first: "Bozhedar", last: "Denisyuk" },
      gender: "male",
      email: "bozhedar.denisyuk@example.com",
      location: {
        country: "Ukraine",
        state: "Poltavska",
        city: "Irshava",
        street: { number: 6275, name: "Miloslavska" },
      },
      dateOfBirth: "66-03-04",
      profilePicture: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
      name: { title: "Miss", first: "Leonor", last: "Zamora" },
      gender: "female",
      email: "leonor.zamora@example.com",
      location: {
        country: "Mexico",
        state: "Chiapas",
        city: "Carrizal Grande",
        street: { number: 7496, name: "Prolongación Sinaloa" },
      },
      dateOfBirth: "99-10-14",
      profilePicture: "https://randomuser.me/api/portraits/women/54.jpg",
    },
    {
      name: { title: "Mr", first: "Theodore", last: "Jones" },
      gender: "male",
      email: "theodore.jones@example.com",
      location: {
        country: "New Zealand",
        state: "Nelson",
        city: "Wellington",
        street: { number: 641, name: "Pages Road" },
      },
      dateOfBirth: "74-07-11",
      profilePicture: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
      name: { title: "Ms", first: "Johanne", last: "Jensen" },
      gender: "female",
      email: "johanne.jensen@example.com",
      location: {
        country: "Denmark",
        state: "Sjælland",
        city: "Nykøbing F",
        street: { number: 2883, name: "Svalevej" },
      },
      dateOfBirth: "81-01-04",
      profilePicture: "https://randomuser.me/api/portraits/women/50.jpg",
    },
    {
      name: { title: "Mr", first: "Allen", last: "Carpenter" },
      gender: "male",
      email: "allen.carpenter@example.com",
      location: {
        country: "United States",
        state: "Oklahoma",
        city: "Huntington Beach",
        street: { number: 7235, name: "E North St" },
      },
      dateOfBirth: "98-09-25",
      profilePicture: "https://randomuser.me/api/portraits/men/85.jpg",
    },
    {
      name: { title: "Miss", first: "Laura", last: "Shaw" },
      gender: "female",
      email: "laura.shaw@example.com",
      location: {
        country: "United Kingdom",
        state: "Herefordshire",
        city: "St Davids",
        street: { number: 8727, name: "St. John’S Road" },
      },
      dateOfBirth: "50-03-30",
      profilePicture: "https://randomuser.me/api/portraits/women/92.jpg",
    },
    {
      name: { title: "Ms", first: "Taimara", last: "Gonçalves" },
      gender: "female",
      email: "taimara.goncalves@example.com",
      location: {
        country: "Brazil",
        state: "São Paulo",
        city: "Eunápolis",
        street: { number: 1339, name: "Rua Dezenove de Outubro" },
      },
      dateOfBirth: "77-11-22",
      profilePicture: "https://randomuser.me/api/portraits/women/88.jpg",
    },
    {
      name: { title: "Mr", first: "Felipe", last: "Olmos" },
      gender: "male",
      email: "felipe.olmos@example.com",
      location: {
        country: "Mexico",
        state: "Puebla",
        city: "Chaucingo",
        street: { number: 1768, name: "Calle Norte Varela" },
      },
      dateOfBirth: "63-11-14",
      profilePicture: "https://randomuser.me/api/portraits/men/51.jpg",
    },
    {
      name: { title: "Ms", first: "Anabel", last: "Guajardo" },
      gender: "female",
      email: "anabel.guajardo@example.com",
      location: {
        country: "Mexico",
        state: "Aguascalientes",
        city: "Zacamulpa",
        street: { number: 7745, name: "Continuación China" },
      },
      dateOfBirth: "60-05-05",
      profilePicture: "https://randomuser.me/api/portraits/women/58.jpg",
    },
  ];