INSERT INTO `WASHING_MACHINE` (`BUILDING`, `FLOOR`, `NUMBER`, `OUT_OF_ORDER`)
    VALUES ('A', 4, 1, TRUE);
INSERT INTO `WASHING_MACHINE` (`BUILDING`, `FLOOR`, `NUMBER`, `OUT_OF_ORDER`)
    VALUES ('A', 4, 2, TRUE);
INSERT INTO `WASHING_MACHINE` (`BUILDING`, `FLOOR`, `NUMBER`, `OUT_OF_ORDER`)
    VALUES ('A', 8, 1, TRUE);
INSERT INTO `WASHING_MACHINE` (`BUILDING`, `FLOOR`, `NUMBER`, `OUT_OF_ORDER`)
    VALUES ('A', 8, 2, FALSE);