INSERT INTO USER (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (10, 0, 'admin', 'admin', 'ADMIN');

INSERT INTO USER (ID, VERSION, USERNAME, PASSWORD, ROLE) VALUES (11, 0, 'alma', 'korte', 'USER');


